name: Send Email Workflow

on:
  workflow_dispatch: # Permet de déclencher manuellement
  push:              # Déclenche le workflow lors d'un push
    branches:
      - main

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Send Email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.ACCOUNT }}
        password: ${{ secrets.MAIL_PASSWORD }}
        from: adebola
        to: waximum@gmx.com
        subject: "Mail title"
        body: "This is the body of the email."
        attachments: README.md