name: Send Email Workflow

on:
  workflow_dispatch: # Permet de déclencher manuellement
  push:              # Permet de déclencher lors d'un push sur la branche principale
    branches:
      - main

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Send Email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.ACCOUNT }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: mail title
        body: This is the body of the email.
        to: waximum@gmx.com
        from: ${{ secrets.MAIL_ADDRESS }}
        content_type: text/plain
        attachments: README.md